### ISSUE TITLE
compiling kernel with -march for specific devices

### ISSUE THREAD

**Issue by NeroReflex** [ChimeraOS/linux-chimeraos#2]
From my tests on my PC compiling the kernel (xanmod) with -march=znver3 makes battlefield 5 runs better, a small amount, about 4 FPS over 140+ and mhrise by about the same amount, but something that can be measured nontheless.

Therefore I also compile mesa with such an argument and can see another improvement, but since I removed from mesa a lot of unneeded stuff (Microsoft stuff, VMware stuff, libunwind and intel) I can't say the exact improvement and can only say that the overall improvement of doing this for important stuff graphics-related components is sizeable.

There is also the possibility of compiling with -mtune that should not break the binary for other targets, but it might hurt performance on those other targets and regressions would be more difficult to find.  I wouldn't consider it as an option, but I want to inform the reader about this possibility.

Overall, for a desktop PC the hassle of compiling mesa and the kernel with that flags gives nice results paing back for those hours of compilation and it would be nice to see that for at least popular hardware (like the rog ally and the steam deck). However that means compiling a realease for each and every "notable" device and it will require time (not very much other resources as my assumption is that the device already works) therefore the discussion can continue from this point, weighting required time for the team and end-user experience. Maybe someone can test on a rog ally with some more games that bfv and mhr.

**Comment by NeroReflex** [comment]
This seems to be a fair assumption but should it be required for the user to know about the flag to have the gain (if any, that has still to be tested))?  Maybe for those devices it is possibile to have a dedicated ISO compiled by someone in charge of doing that? This would allow the possibility of not including device-specific quirks in the generic system image and spare a few mb while also providing the end user with the best possibile experience.

**Comment by Samsagax** [comment]
Doesn't really makes sense for a wide hardware range as we target.
